### ISSUE TITLE
Embed static ressources into the ppl-utils binary.

### ISSUE THREAD

**Issue by jyaif** [jyaif/ppl-utils#2]
The ppl-utils binary and the static files (pewpewlive-wasm.js, pewpewlive-wasm.wasm, pewpew.html) need to stay in sync.
To prevent user error it would be nice if the static files were stored in the binary.

Packr seems like it would do the job: https://github.com/gobuffalo/packr
[edit: Go 1.16 will support this natively! No need to use Packr]

**Comment by ModEngineer** [comment]
I prefer to compile my own binaries, so how would this affect me? Keeping static files externally would mean that I wouldn't have to recompile the binary all that often. This could be implemented in a way where the releases(i.e. prebuilt binaries) or a separate branch use this system without touching the main branch.

**Comment by ModEngineer** [comment]
As a side note in relation to my previous comment, using something like Git or GitHub Desktop allows you to sync all files automatically, thus making it easier to update the entire local clone of the repository.

**Comment by jyaif** [comment]
This change would impact you negatively. Note however that compiling ppl-utils should be trivial.

**Comment by ModEngineer** [comment]
It is trivial to compile ppl-utils, which is why I'm not necessarily in favor of this change, though I understand the convenience of it.

**Comment by jyaif** [comment]
I really prefer the simplicity of having a single binary.
I suppose that one solution to your problem would be for ppl-utils to serve the built-in webasm files by default, but offer the possibility to override the served files.
Overriding the served files could for instance be done via arguments on the command line.

**Comment by ModEngineer** [comment]
I understand. It's annoying for most people to have to redownload the entire repository _and_ release each time a small update is made to the Webassembly.
