### ISSUE TITLE
Shield Floating Message

### ISSUE THREAD

**Issue by TheAssassin-Kira** [jyaif/ppl-utils#4]
In ["/dynamic/helpers/boxes/shield_box.lua"] line 37 we have ```-- local new_message = floating_message.new(x, y, "Shield +1", 1.5, 0xffff00ff, 3)``` so maybe change it to ```local new_message = floating_message.new(x, y, "Shield +1", 1.5fx, 0xffff00ff, 3)``` before hand so as to get a floating message by default rather then changing it each update as it is a bit forgetful for me and also an arrow by default would be nice :sweat_smile:

**Comment by SKPG-Tech** [comment]
You could change the code yourself, and make a pull request. That way everyone when they update the helpers will have the new version.

**Comment by Tasty-Kiwi** [comment]
#9 This fix has been implemented.
